### ISSUE TITLE
Deploying a project (Stored Procedures and User Defined Functions)

### ISSUE THREAD

**Issue by ThomasLieser** [IBM/db2forzosdeveloperextension-about#120]
Currently we are still relying on Datastudio to deploy complete folders of stored procedure and user defined functions.
That functionality would help to deploy projects containing a lot of StPs and UdFs (we have now systems containg several hundred)

**Comment by katsoohoo** [comment]
Hi @ThomasLieser,

Thanks for letting us know about this feature as well. We'll take a look at #119 first before this one.

Happy Holidays!

**Comment by ThomasLieser** [comment]
@katsoohoo thanks a lot - sounds good! and: Happy Holidays to you as well!

**Comment by ThomasLieser** [comment]
@katsoohoo One additional information - as we are heavily using StPs/UdFs in DB2 V12 and Datastudio does not support V13 we will have to postpone the migration to V13.
We will be very glad when we can migrate to VSCode - Thanks again for your support

**Comment by b-tsao** [comment]
Hi @ThomasLieser, in developer extension 2.1.5 release we now support external SQL and Java stored procedure deployment. Could you specify more information about the nature of stored procedures your team deploys for more information to help us prioritize?

Thanks!

**Comment by ThomasLieser** [comment]
@b-tsao Thanks for your question.

We are using Native SQL StoredProcedures and UserDefinedFunctions - the system I'm working on currently has about 600 native StPs and UdFs - there are systems in our company that also use StPs and UdFs (but our system was an early adopter, so we have the biggest number). 

The process for deployment is as follows:
- the developer deploys in test and integration environments (in my case about 10 different environments, because our software is used by several companies) - we use Datastudio and GIT
- during deployment to production the DBA checks out the "release branch" and deploys it to the productive environment - obviously the DBA does this now using the functionality of Datastudio that deploys "all" StPs or UdFs in "one" go - he doesn't need to know which to select - he just deploys all (with a new "version"). When the "release" is activated (this is a process over all systems in the house) he just activates all StPs and UdFs of that "version" (this has helped us a lot as we can deploy some time before the activation, makes it much easier)

**So what would we need?**
a) be able to deploy native UdFs as well
b) deploy "all" UdFs and StPs in a folder or project in one go

I do like the developer extension - but without these two features we can't move our projects from Datastudio as you will understand. On the other hand time is running short for us - we've already had to postpone moving to DB2 V13 as Datastudio is not supported there.

Thanks for your help

**Comment by ThomasLieser** [comment]
@b-tsao To add: **it would be good to know what you plans are** - if the features we need to replace Datastudio are not on your schedule for 2024 we will have to start looking for alternative solutions (though I'm afraid they will be very cumbersome and so far I know of no other replace for Datastudio) - as we will need to move on to V13 next year.

**Comment by ThomasLieser** [comment]
@katsoohoo @b-tsao @ericradz 
So, I'm giving it one last try - can anybody say something about what is planned for the future? 
2025 is getting nearer - and once we need to move on to V13 we need a replacement for Datastudio.
If our needs are not on your list, we will have to think about a work-a-round solution.
Sorry to keep pesting you but this a important topic for us

**Comment by b-tsao** [comment]
Hi @ThomasLieser,

I apologize about the lack of response. I have notified @amadhavia a few weeks ago about your requirements and she would be the proper person to provide the information you seek.

We do actively work to meet the needs of our users and consider every issue carefully.

**Comment by ThomasLieser** [comment]
@b-tsao thanks

**Comment by amadhavia** [comment]
@ThomasLieser Please send me an e-mail to mamirne@us.ibm.com. I will be happy to further discuss about your requirements and the roadmap and see how we can better assist you. 

Regards, 
Madhavi Amirneni

**Comment by ThomasLieser** [comment]
@amadhavia eMail sent - thanks

**Comment by DebbieB1** [comment]
Hello, our team is also facing this challenge.  We have a quickly growing number of Native Db2 SQL stored procedures and are trying to transition from DataStudio to the Developer's Extension, paired with BitBucket. 

One of the limitations listed of the Developers Extension is that it cannot handle NSP with input parameters of a datatype Array.     I also have an example where it seems unable to handle a NSP with an output parameter of datatype Array.    

Our roadmap has us moving to Db2 v13 by the end of the year.    It sounds like we may have to postpone that until VSCode catches up?   Is there an ETA please?

**Comment by ThomasLieser** [comment]
@DebbieB1 I was wondering that nobody else was facing that problem. Our deadline for DB2V13 is the end of 2025 (which of course means having tested everything on a test LPAR at least by September 2025).
I'm still hoping to get a full solution in the VSCODE db2Extension well before that date....

**Comment by DebbieB1** [comment]
Have there been any updates on the status of enhancements for handling Arrays as input/output data types?   My team is working in Developer's Extension, but we have to continue to return to Data Studio to test many of our Db2 Native Stored Procedures.  

Our v13 upgrade is on hold until this is resolved.  If anyone has an ETA, I'd appreciate it.

**Comment by amadhavia** [comment]
@DebbieB1 We are currently working on the key features that are requested above (https://github.com/IBM/db2forzosdeveloperextension-about/issues/120#issuecomment-2022092264) like --

a) be able to deploy native UdFs as well
b) deploy StPs in a folder or project in one go 
Able to deploy and debug SQLJ procedures, etc. We plan to release these features in our upcoming October release. 

We will look into handling the Arrays as input/output for the procedures soon after the above features. 

Regards, 
Madhavi Amirneni

**Comment by DebbieB1** [comment]
@amadhavia 
 Thank you for you quick reply!   I will pass that along to upper management to set expectations.

**Comment by mykael22000** [comment]
You can put together a utility that grabs a bunch of stored procedures and imbeds them into a batch job.  Just upload it and submit it to deploy them...

**Comment by ThomasLieser** [comment]
> You can put together a utility that grabs a bunch of stored procedures and imbeds them into a batch job. Just upload it and submit it to deploy them...

Try that with UTF8, hundreds of StPs and UdFs, several schemata to deploy to and so on - not really a valid scenario.

And we are using GIT - I want a controlled way of deploying

**Comment by DebbieB1** [comment]
@amadhavia.    I do not see a ticket open for the Stored Procedure testing shortcomings in the Developer's Extension (Array handling).     Is there an open item and is there an expected timeline?  We are now 6 months out from the last response and I haven't heard or seen anything else.  

We will be converting to Db2 v13 this year and our ability to test with VSCode will not be sufficient.  We will lose Data Studio and be in a difficult position.

**Comment by amadhavia** [comment]
Hi @DebbieB1 , 

We have delivered the deploying the stored procedures and UDFs in a folder in one go, and deploy, debug SQLJ procedures in our  2.2.0 release. 

Currently working on deploying, debugging of UDFs in this upcoming release.  

We will look into handling the Arrays as input/output for the procedures soon after the above features. This is still is high in our priority list. Thank you for your patience. 

Regards,
Madhavi Amirneni

**Comment by DebbieB1** [comment]
Thank you!  We have put off our upgrade to v13 about as long as we can.   When you have a release timeline projected, I would appreciate an update.

**Comment by ThomasLieser** [comment]
@DebbieB1 
> 
> We will be converting to Db2 v13 this year and our ability to test with VSCode will not be sufficient. We will lose Data Studio and be in a difficult position.

**We are in the same situation** - I'm still hoping to see the features we need soon in db2Extension.
If not we'll probably use a build/deploy based on the GIT repository - but only if we have no better way of doing it.

**Comment by kumari-mani** [comment]
Hi @DebbieB1 , @ThomasLieser , @mykael22000  , We have implemented `Deploying a project (Stored Procedures and User Defined Functions) ` feature in 2.2.1. Please verify.

**Note:**
- Running `stored procedure` do supports the array type as an argument.
- Running `user-defined-function` does not support the array type as an argument for now.
- Debugging `stored procedure` does not support the array type as an argument for now.

**Comment by DebbieB1** [comment]
Exciting!

I do see that you can select an array type for Stored Procedure testing now.   However after working with it for a few hours, I'm still not able to get it to work.    Based upon the instructions on the screen, I am entering a CHAR(8) array with the values in square brackets, delimited by semicolon.   I've tried different variations of using ', ", and no quotes at all.    I've also tried curly-brackets with the same results.  Always I get a -440.   I can run the same Stored Procedure, same environment, same input, using Data Studio and the response is successful so I know my procedure is in place and works.

I've also attempted to use an Integer Array but have the same results.  It works in DS, but not in the Developer's extension.  I am on version 2.2.1, released 04/04/2025.   

I can provide you my examples if it would help.

**Comment by kumari-mani** [comment]
@DebbieB1 Could you provide your examples, SP? So that we can investigate from our end.

**Comment by DebbieB1** [comment]
@kumari-mani  I've attached a document containing a simple Stored Procedure with an INPUT array and the DDL for the User Defined Datatype.    This shows the error that I receive in Developer's Extension & a successful return using Data Studio for comparison.

[Developers Extension Array Test.docx](https://github.com/user-attachments/files/19915503/Developers.Extension.Array.Test.docx)

Please let me know if you need any more information.

**Comment by DebbieB1** [comment]
Hi @kumari-mani .      I don't know if you want to open a different Issue for our problem?   I think the scope of this has crept to something different than the Developer's Extension.

I have upgraded to the latest JDK and am now getting a different message, one that we've struggled with before, with both DS and VSCode.    I'd be willing to bet that you have your connections formed directly to your DDF ports?  We are required to go through a middleware server with Db2 Connect on it to comply with our Authorized Users licensing.

When I go straight to my DDF ports with Data Studio, the procedure works.
When I go through the Db2 Connect service with DS, the procedure fails.

When I go straight to my DDF ports with VS  Code, I get licensing errors and can't even connect.   Data Studio is getting to resources that VS Code apparently can't.
When I go through the Db2 Connect service with VS Code, the procedure fails as I've shown.

I think we need to understand how licensing applies to the Developer's Extension connections.    I can't imagine that all companies are required to get Db2 Connect for their developers to connect.  It seems to me as if Db2 Connect in the middle is causing the problems that we're seeing.

**Comment by amadhavia** [comment]
@DebbieB1 Hi Debbie, 
As you are facing a different issue than the original enhancement request (which has been fulfilled in the latest release), I would recommend closing this issue and opening a new issue. 
In the new issue, please do provide the steps that you are performing to run the stored procedure along with the authority of the user id being used. 
Also, did you specify the path of the Db2 connect license file in the configuration? 
Here's the doc. link which shows how to configure the JDBC driver license -- https://github.com/IBM/db2forzosdeveloperextension-about?tab=readme-ov-file#setting-the-jdbc-license-and-jdbc-driver-files

Regards, 
Madhavi Amirneni

**Comment by DebbieB1** [comment]
@amadhavia , will do, thank you and your team so much for your help!

**Comment by ThomasLieser** [comment]
@kumari-mani 
So sorry I'm giving feedback so late - we're very happy about this feature - works nicely for us. We are in the middle of moving our repositories/projects to VSCODE/db2Extension - so I forgot to answer

**Comment by DebbieB1** [comment]
> [@DebbieB1](https://github.com/DebbieB1) Hi Debbie, As you are facing a different issue than the original enhancement request (which has been fulfilled in the latest release), I would recommend closing this issue and opening a new issue. In the new issue, please do provide the steps that you are performing to run the stored procedure along with the authority of the user id being used. Also, did you specify the path of the Db2 connect license file in the configuration? Here's the doc. link which shows how to configure the JDBC driver license -- https://github.com/IBM/db2forzosdeveloperextension-about?tab=readme-ov-file#setting-the-jdbc-license-and-jdbc-driver-files
> 
> Regards, Madhavi Amirneni

@amadhavia  Hi Madhavi,  we are still facing connection problems from VSCode to our DDF ports.  Our system programmer is going to take up this issue with Support.  We can connect with DS and we just can't figure out what's missing with VS Code.  Unless DS just really wasn't using licensing much due to it's age.      I have nothing else to add to this Issue and it's resolution.    Once we get our connection, I will re-test the new functionality - Arrays as Parameters - and open another Issue if I still have problems getting it to work.

**Comment by DebbieB1** [comment]
@amadhavia  Hello Madhavi!   I just wanted to let you know that we finally have our issue resolved with the Developer's Extension connection to the DDF.  With that in place (rather than using an intermediate server for credentials), the Array input/output functionality is working perfectly for us now.
